backend/question-service/__tests__/index.test.ts, backend/question-service/__tests__/routes/question.routes.test.ts, backend/question-service/jest.config.js, backend/question-service/package-lock.json, backend/question-service/package.json, backend/question-service/src/common/config.util.ts, backend/question-service/src/common/logger.util.ts, backend/question-service/src/common/mongodb.util.ts, backend/question-service/src/index.ts, backend/question-service/src/routes/question.routes.ts, backend/question-service/src/server.ts, backend/question-service/src/types/Config.ts, backend/question-service/tsconfig.json, package-lock.json
Notes:
- Added the express async handler package. This package simplifies handling async errors, removing the need to use try catch blocks
=> Setup question service project and dependencies

frontend/components/layout/layout.tsx, frontend/components/layout/navbar.tsx, frontend/styles/globals.css
=> Make minor UI fixes

frontend/components/layout/navbar.tsx, frontend/tsconfig.json
Change route for landing page in navbar
=> Fix home route

frontend/components/layout/layout.tsx, frontend/components/layout/navbar.tsx, frontend/styles/globals.css
=> Fix routing to home page from navbar issue

frontend/components/customs/datatable.tsx, frontend/mock-data/index.ts, frontend/pages/sessions/columns.tsx, frontend/pages/sessions/index.tsx, frontend/types/datatable.ts, frontend/types/index.ts, frontend/types/session.ts
=> Add UI for sessions route with mock data

frontend/components/customs/datatable.tsx, frontend/services/axios-middleware2.ts, frontend/services/question-service-api.ts
**Resolves**
- Minor Questions datatable pagination display issue
=> fix: bug fix for milestone 2

backend/matching-service/src/common/logger.util.ts, backend/matching-service/src/common/rabbitmq.util.ts, backend/matching-service/src/services/rabbitmq.service.ts, packages/user-types/src/Proficiency.ts
=> Implement Waiting Queue

backend/matching-service/src/types/MatchedPair.ts
added: data type for the returned object from matched users
=> Add schema for matched users

backend/question-service/src/controllers/question.controller.ts, backend/question-service/src/models/question.repository.ts, backend/question-service/src/routes/question.routes.ts, backend/question-service/src/types/SortedComplexity.ts
Added new endpoint to retrieve random question based on category and complexity. 
Updated repository to retrieve the question
Updated controller with relevant handler function to retrieve question
=> Add query function by topic and complexity

docker-compose.yml
=> Matching Service Dockerisation

backend/matching-service/src/controllers/matching.controller.ts, backend/matching-service/src/services/rabbitmq.service.ts, backend/matching-service/src/services/ws.service.ts, backend/matching-service/src/types/IUserQueueMessage.ts, backend/matching-service/src/types/UserQueueRequestDto.ts, frontend/components/dashboard/new-session.tsx, frontend/services/matching-service-api.ts, frontend/types/matching-api.ts, packages/ws-types/src/WebSocketMessageType.ts
Add validation to check is user already has a match before inserting into entry queue
Integrate successful matching with ws
=> Integrate successful matching with ws

backend/matching-service/src/services/rabbitmq.service.ts, backend/matching-service/src/services/ws.service.ts
**Feature**
- On Dead Letter Message consumed, the WSS will be notified to close the corresponding client connection
**Resolves**
- #125
=> Integrate DLQ with WS

backend/matching-service/src/controllers/matching.controller.ts, backend/matching-service/src/services/rabbitmq.service.ts, backend/matching-service/src/services/ws.service.ts, frontend/components/dashboard/new-session.tsx, frontend/services/matching-service-api.ts, frontend/types/matching-api.ts
=> Integrate UI with WS connection on match request

backend/matching-service/package.json, backend/matching-service/src/index.ts, backend/matching-service/src/services/rabbitmq.service.ts, backend/matching-service/src/services/ws.service.ts, docker-compose.yml
Fix: add ws-types into dev dependencies
=> add ws dependency

backend/collaboration-service/package.json, backend/collaboration-service/src/types/CollabDto.ts, backend/collaboration-service/src/types/IChat.ts, backend/collaboration-service/src/types/LanguageMode.ts, backend/collaboration-service/src/types/index.ts, package-lock.json
=> Create db schema for Collaboration Service

frontend/components/layout/layout.tsx, frontend/components/layout/navbar.tsx, frontend/pages/code/index.tsx
**New Features**
- Fix navbar to page top
- Remove global page height restriction
- Add logic to hide navbar on certain pages
=> Fix navbar to top of page

.github/workflows/cd.yml, .github/workflows/ci.yml, backend/matching-service/src/controllers/matching.controller.ts, backend/matching-service/src/server.ts, backend/matching-service/src/services/rabbitmq.service.ts, backend/matching-service/src/services/ws.service.ts, backend/user-service/src/common/mail.util.ts, docker-compose.local.yml, docker-compose.yml, frontend/components/dashboard/new-session.tsx, frontend/pages/api/auth/[...nextauth].ts, frontend/services/axios-middleware.ts, frontend/tsconfig.json, nginx/templates/local-nginx.conf.template, nginx/templates/nginx.conf.template
The deployed backend server is accessible with the URL https://peerprep.glemenneo.com/api
=> 121 be deploy to vps

backend/question-service/__tests__/routes/question.routes.test.ts, backend/question-service/src/common/autoinsert.util.ts, backend/question-service/src/common/mongodb.util.ts, backend/question-service/src/controllers/question.controller.ts, backend/question-service/src/server.ts, backend/user-service/__tests__/routes/user.routes.test.ts, backend/user-service/src/controllers/auth.controller.ts, backend/user-service/src/controllers/user.controller.ts, frontend/pages/questions/index.tsx, frontend/services/question-service-api.ts, frontend/types/question.ts
=> 176 be fe all services refactor error messages to be more detailed

backend/collaboration-service/package.json, backend/collaboration-service/src/server.ts, backend/collaboration-service/src/services/collab.service.ts, backend/collaboration-service/src/services/socketio.service.ts, backend/matching-service/src/controllers/matching.controller.ts, backend/matching-service/src/models/matching.repository.ts, backend/matching-service/src/routes/matching.routes.ts, frontend/components/customs/custom-avatar.tsx, frontend/components/dashboard/new-session.tsx, frontend/components/ui/tooltip.tsx, frontend/package.json, frontend/pages/api/auth/[...nextauth].ts, frontend/pages/code/[id]/index.tsx, frontend/pages/code/editor.tsx, frontend/pages/code/language-mode-select.tsx, frontend/services/axios-middleware.ts, frontend/services/question-service-api.ts, frontend/types/index.ts, frontend/types/language-mode.ts, frontend/types/question.ts, package-lock.json
Closes #137 
Note: This was branched off from my Socket.IO PR thats why the files changed are a lot. Merge the previous one before this.
=> Support Changing of Languages

backend/matching-service/src/controllers/matching.controller.ts, backend/matching-service/src/models/matching.repository.ts, backend/matching-service/src/routes/matching.routes.ts, backend/matching-service/src/types/MatchDto.ts
=> Retrieve paginated past sessions from BE
